[package]
name = "secretstore"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5"
clap = { version = "4.5.40", features = ["derive"] }
dirs = "6.0.0"
hex = "0.4.3"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
